#+TITLE: Char in C++
#+AUTHOR: Angel Dhakal
#+DATE: 2025-11-21
#+DESCRIPTION: Char is a character data type in C and C++ that is used to represent single ASCII character.
#+KEYWORDS: c++, system, char, text, ascii
#+OPTIONS: ^:{} num:nil toc:5
#+HTML_HEAD: <meta name="pub_date" content="2025-11-21" />
#+HTML_HEAD: <meta name="updated_date" content="2025-11-21" />
#+EXPORT_FILE_NAME: /home/angel/xynapz/angeld.me/src/content/post/char-in-cpp.html

* Introduction
Char is a character data type in C and C++ that is used to represent single *ASCII* character. It is the building block for string which is basically just a list of characters. A char actually stores an integer value that coressponds to a ASCII code. There are many types of chars like, *char* (signedness is implementation defined), *signed char*, *unsigned char*, *char8_t*, *char16_t*, and *char32_t* important ones are discussed in this post. Understanding char is a must if you want to have a very good understanding of strings and text processing.

| Type          | Size     | Range                                            |
| char          | 1 Byte   | Implementation Defined (-128 to 127 *OR* 0 to 255) |
| unsigned char | 1 Byte   | 0 to 255                                         |
| signed char   | 1 Byte   | -128 to 127                                      |
| w_char        | 2-4 Byte | Implementation Defined                           |
| char_8        | 1 Byte   | For UTF-8 Encoding                               |
| char_16       | 2 Byte   | For UTF-16 Encoding                              |
| char_32       | 4 Byte   | For UTF-32 Encoding                              |

* char
char data type is a byte sized (typically *1 Byte* but not always) integral data type that is used to store characters in ASCII format. It is implementation defined meaning it can be any of *signed* or *unsigned* chars, so user should not make any assumption that it is either signed or unsigned. Depending on if it is signed or unsigned, it can store values from and up to *(-128 to 127)* and *(0 to 255)* respectively. When we assign a character literal to a variable, the compiler does a ASCII table lookup and replaces that character with its equivalent numeric ASCII value.
