#+TITLE: Regular Expressions
#+AUTHOR: Angel Dhakal
#+DATE: 2025-12-17
#+DESCRIPTION: Documentation on regular-expression with bash.
#+KEYWORDS: bash, mastery, documentation, technical-docs, regular-expression, pattern-matching, string-matching, text-matching, linux, linux-docs, shell
#+OPTIONS: ^:{} num:nil toc:5 html-postamble:nil
#+XZHH_PUB_DATE: 2025-12-17
#+XZHH_UPDATED_DATE: 2025-12-17
#+EXPORT_FILE_NAME: /home/angel/xynapz/angeld/site-content/knowledge_base/linux/bash/regular-expressions.html
#+XZHH_ORDER: 8

* Regular Expressions
Regular Expression pvovides a language for performing pattern matching, data extraction and heavy text processing. They are not just in bash but everywhere in computer science, where text manipulation and processing involves like, text editors, find-and-replace, a lot of technologies use regular expressions to find a pattern of text in a large pool of text object.

In bash utilities like sed, grep, etc use regular expression for processing text. SO understanding them is a must if my goal is to master bash.

** Mechnish and Syntax
In bash, the use of *=[[]]=*  double bracket is used whenever we want to do some pattern matching using regex (regular-expression), alongside the *=~* operator, the reason for double brackets unlike single braces is because double brackets directly performs the operation by treating the contents inside of brackets as pure regex and not performing any kind of [[file:quoting-expansions.org::*Shell Expansion][Shell Expansion]], that would be an invalid regex syntax.

#+begin_src bash
my_string="cat"
if [[ $my_string =~ c.t ]]; then
    # commands
    echo "Hello"
else
    echo "World"
fi
#+end_src

#+begin_example
Hello
#+end_example
Here, the dot(*.*) between c, t, is a regular-expression metacharacter (a character that has a special meaning in regex) that means match any single character. Some other metacharacters are given below on a table.
