#+TITLE: Variables
#+AUTHOR: Angel Dhakal
#+DATE: 2025-12-17
#+DESCRIPTION: Documentation on bash variables.
#+KEYWORDS: bash, mastery, documentation, technical-docs,variables, containers, data, types, data types, global variables, local variables, keywords, identifiers, reserved keywords, linux, linux-docs, shell
#+OPTIONS: ^:{} num:nil toc:5 html-postamble:nil
#+XZHH_PUB_DATE: 2025-12-17
#+XZHH_UPDATED_DATE: 2025-12-17
#+EXPORT_FILE_NAME: /home/angel/xynapz/angeld/content/writings/linux/bash/variables.html
#+XZHH_ORDER: 5

* Variables
As any other programming language, a bash is just a named identifier for a data object. There are two types of variables in bash, *global* variables and *local* variables.

** Global Variable
A global variable is a variable that is available in all the shells in a system. It is also called environment variables. They are named *ALL_CAPS* to denote they are global or environment variables. They can be set in shell configuration files which makes it available to all available shells. In a shell, we can view all global variables using *env* or *printenv* commands.

#+begin_src bash
  env
#+end_src

#+begin_example
| SHELL=/usr/bin/zsh                                                                                      |
| HYPRLAND_CMD=Hyprland                                                                                   |
| XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1                                               |
| XDG_BACKEND=wayland                                                                                     |
| DESKTOP_SESSION=hyprland                                                                                |
| XDG_SEAT=seat0                                                                                          |
| PWD=/home/angel/xynapz/site-content/knowledge_base/linux                                                |
| XDG_SESSION_DESKTOP=Hyprland                                                                            |
| LOGNAME=angel                                                                                           |
| XDG_SESSION_TYPE=wayland                                                                                |
| _=/usr/bin/env                                                                                          |
| MOTD_SHOWN=pam                                                                                          |
| HOME=/home/angel                                                                                        |
| LANG=en_US.UTF-8                                                                                        |
| _JAVA_AWT_WM_NONREPARENTING=1                                                                           |
| XDG_CURRENT_DESKTOP=Hyprland                                                                            |
| WAYLAND_DISPLAY=wayland-1                                                                               |
| XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0                                                     |
| XDG_SESSION_CLASS=user                                                                                  |
| TERM=dumb                                                                                               |
| USER=angel                                                                                              |
| HYPRLAND_INSTANCE_SIGNATURE=386376400119dd46a767c9f8c8791fd22c7b6e61_1765440446_1500978115              |
| DISPLAY=:1                                                                                              |
| SHLVL=1                                                                                                 |
| MOZ_ENABLE_WAYLAND=1                                                                                    |
| XDG_VTNR=1                                                                                              |
| XDG_SESSION_ID=2                                                                                        |
| XDG_RUNTIME_DIR=/run/user/1000                                                                          |
| DEBUGINFOD_URLS=https://debuginfod.archlinux.org                                                        |
| PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl |
| DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus                                                   |
| MAIL=/var/spool/mail/angel                                                                              |
| OLDPWD=/home/angel                                                                                      |
#+end_example

** Local Variables
Local Variables are variables that are available in the current shell only. In some conventions local variables are all capitalized and in some conventions they are not. So its up to the user to follow a style for naming their own local variables, but being consistent here is the key.

** Types of Variables
The variables in bash has four main types, they are:
- Integer Variables
- String Variables
- Constant Variables
- Array Variables

** Creating Variables
Variables in bash are case-sensitive, naming a variable is simple in bash, you can give any name, but giving a variable a name that starts with a digit is an error.

#+begin_src bash
  1name="Angel"
  echo "$1name"
#+end_src

#+begin_example
name
bash: line 1: 1name=Angel: command not found
#+end_example

*** Space around equals (=) sign
Giving a space around equal sign will result in an error. Examples

#+begin_src bash
  name = "Angel"
  echo "$name"
#+end_src

#+begin_example
: bash: line 1: name: command not found
#+end_example

#+begin_src bash
  name="Angel"
  echo "$name"
#+end_src

#+begin_example
Angel
#+end_example
Above in the the first example, if you look closely, there is space around *=* while assigning *Angel* to name, this is not allowed while creating a variable in bash, the second code block which doesn't have any leading or trailing space around *=* sign, is valid syntax to create a variable in bash.

*** Exporting a Variable
A variable that we create is only available in that shell, if we want a variable to exists for all of its child-shell also called subshells, child-process, etc. then we can export a variable using the *export* keyword, what that does, is, it basically exports that variables for all of its child-process to access it, even modify it, but the modified variables only exists within that child-shell or its children shells, but not in the parent shell, it still has its original reference.

#+begin_src bash
  export name='Angel'
#+end_src

In above example, the name variable will be available to the child shell that this command is run on.
** Reserved Keywords
Since bash is a extension of sh, all the reserved keywords of sh are also reserved in bash, plus there are a few more reserved keywords that bash has, so naming our variables, that is not a reserved keyword is a compulsory. Some examples are, *HOME*, *PATH*, *PS1*, *SHELL*, etc.
