#+TITLE: Gentoo Installation and Setup
#+AUTHOR: Angel Dhakal
#+DATE: 2025-12-22
#+DESCRIPTION: This post is my prefered installation and setup of gentoo linux distribution.
#+KEYWORDS: linux, kernel, system, installation, install, setup, bare-metal, systemd
#+OPTIONS: ^:{} num:nil toc:5 html-postamble:nil
#+HTML_HEAD: <meta name="pub_date" content="2025-12-22" />
#+HTML_HEAD: <meta name="updated_date" content="2025-12-22" />
#+EXPORT_FILE_NAME: /home/angel/xynapz/angeld/site-content/knowledge_base/linux/gentoo-installation-and-setup.html

* Gentoo Installation & Setup
This is my guide and walkthrough of installing and setting up a reproducable gentoo environment. The packages installed here are the ones I use, as I dont like random packages installed in my system and worse of all, running as a process.

* Download Iso and Creating a Bootable Media
I will be using the Minimal Installation CD provided in the gentoo's website downloads page. After the download is done, I will be burning the iso to my USB type-c pen-drive, which is 32GB in size, which is an overkill for a 700MB gentoo's iso media file. Lets burn the iso to our external drive.

#+begin_src bash
cd Downloads/
sudo dd if=install-amd64-minimal-20251221T154556Z.iso of=/dev/sda bs=4096 status=progress && sync
#+end_src
The above command is copied from gentoo's installation handbook, dd is a linux command line utility, that burns iso files to internal or external storage drives.

* Boot into the installtion media
For booting into the newly created installation media (the pen drive), figure out your boot device selection mebu keybinding from your manufacturer (mine is ~ESC~), reboot your system. During the inital bootup select the gentoo installation medium we created. This will open a menu showing some options to boot to gentoo. Select the first option i.e. ~TODO: INSTALLTION BOOT OPTION~.

* Network Setup
I have an ehternet connection to my laptop, so I dont have to go through the hassle of setting up WiFi, If I ever need to setup WiFi connection, that is not during installation, I'll do that when i need it, so I'll skip that section entirely. The gentoo documentation has a good manual on setting that up check it out.

* Partitioning the disk
Partitioning the disk is not that hard as people mention it be. You just have to understand your particlular storage drive, HDD or SDD, they are default mounted to ~/dev~ directory at the root, first lets understand these so called block devices handle naming and their partitions identifiers. If your storage device is the old Hard-Disks, then its ~/dev/sd{a,b,c}~, if its a Solid-State-Drive, then its ~/dev/nvme0{n1,n2}~. These are called block device handle, and they uniquely represent a storage device. When partitioning them, each partion takes the parent's name as the base, appended with its own identifier like ~sda{1,2}~, ~nvme0n1{p1,p2}~, the thing that is making these two partitions identified as two parts of same device is their name identifiers apart from their parent's base name i.e. ~1, 2, p1, p2~ for this example. This is an easy way to remember block-device handles, so that we dont have to often ~lsblk~ the list of devices.

After that is planning how we want to partition our disks, whether we want to create 3 simple partitions (for efi, swap & root) or we want to create multiple partitions for ~/home, /boot, /etc, /sbin, etc~ then that will be slightly extra works, but not a problem. But my usecase is the simple approach, just create 3 partitions, one for efi, swap and the root file system. To create the partitions from my disks i'll be using ~fdisk~ utility, which is already installed in most of the other linux distributions as well.

*First lets see my current partitions*
#+begin_src bash
lsblk
#+end_src

#+begin_example
| NAME                  | MAJ:MIN | RM | SIZE   | RO | TYPE | MOUNTPOINTS |
| zram0                 |   253:0 |  0 | 4G     |  0 | disk | [SWAP]      |
| nvme0n1               |   259:0 |  0 | 476.9G |  0 | disk |             |
| ├─nvme0n1p1           |   259:1 |  0 | 1G     |  0 | part | /boot       |
| └─nvme0n1p2           |   259:2 |  0 | 475.9G |  0 | part | /var/log    |
| /home                 |         |    |        |    |      |             |
| /var/cache/pacman/pkg |         |    |        |    |      |             |
#+end_example

My goal is to completely wipe my disk and create three partitions for efi, swap and root for my gentoo installation, I'll be replacing arch btw. First action on partitioning is select our drive with fdisk, to furthur do some commands and actions.

** Creating EFI System Partition (ESP)
- Run ~fdisk /dev/nvme0n1~ to enter the interactive menu.
- **Create a fresh Label:** Press ~g~ to create a new empty **GPT** partition table.
- **Partition 1 (ESP):**
  - Press ~n~, select partition ~1~, default first sector, set last sector to ~+1G~.
  - **Type:** Press ~t~, select partition ~1~, enter code ~1~ (EFI System).
- **Partition 2 (Swap):**
  - Press ~n~, select partition ~2~, set last sector to ~+16G~ (Matching RAM size).
  - **Type:** Press ~t~, select partition ~2~, enter code ~19~ (Linux Swap).
- **Partition 3 (Root):**
  - Press ~n~, select partition ~3~, default last sector (Takes remaining space).
  - **Type:** Press ~t~, select partition ~3~, enter code ~20~ (Linux Filesystem).
- **Write Changes:** Press ~w~ to write table to disk and exit.

** Formatting the Filesystems
Since I am prioritizing a robust and modern setup, I will be using **Btrfs** for the root filesystem. Btrfs allows for subvolumes (separating system data from user data) and snapshots, which are invaluable for rolling back updates if something breaks.

#+begin_src bash
# Format the ESP as FAT32 (Required by UEFI)
mkfs.vfat -F 32 -n "EFI" /dev/nvme0n1p1

# Initialize and activate Swap
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2

# Format Root as Btrfs
mkfs.btrfs -L "gentoo" /dev/nvme0n1p3
#+end_src

** Creating Btrfs Subvolumes
Before installing, we need to create the subvolume layout. This separates the root filesystem ~@~ from the home directory ~@home~, making backups and reinstalls significantly cleaner.

#+begin_src bash
# Mount the raw partition temporarily
mount /dev/nvme0n1p3 /mnt/gentoo

# Create subvolumes
btrfs subvolume create /mnt/gentoo/@
btrfs subvolume create /mnt/gentoo/@home
btrfs subvolume create /mnt/gentoo/@snapshots

# Unmount to finalize layout
umount /mnt/gentoo
#+end_src

** Mounting the Subvolumes
Now we mount the specific subvolumes with optimized options. I use ~zstd~ compression to save disk space and increase SSD longevity by reducing write amplification.

#+begin_src bash
# Mount Root (@) with compression and performance options
mount -o noatime,compress=zstd,space_cache=v2,subvol=@ /dev/nvme0n1p3 /mnt/gentoo

# Create mount points
mkdir --parents /mnt/gentoo/{home,efi}

# Mount Home (@home)
mount -o noatime,compress=zstd,space_cache=v2,subvol=@home /dev/nvme0n1p3 /mnt/gentoo/home

# Mount ESP
mount /dev/nvme0n1p1 /mnt/gentoo/efi
#+end_src

* Installing Stage 3 Tarball
** Setting the Date
#+begin_src bash
chronyd -q
#+end_src

** Downloading and Unpacking Stage 3
I am using the **Systemd** profile. Navigate to the mount point and download the stage3 tarball from a mirror (under ~releases/amd64/autobuilds/~).

#+begin_src bash
cd /mnt/gentoo
# Use 'links' to find the URL for stage3-amd64-systemd-mergedusr
# Download the tarball
wget <stage3_url>

# Unpack preserving extended attributes (crucial for systemd)
tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner
#+end_src

* Configuring Compilation Options (make.conf)
This file dictates how Portage compiles every package.
#+begin_src bash
nano -w /mnt/gentoo/etc/portage/make.conf
#+end_src

My standard configuration:
#+begin_src conf
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# Parallel compilation: (Total Threads + 1)
MAKEOPTS="-j13"

# Accept all licenses (for firmware/microcode)
ACCEPT_LICENSE="*"

# Video Cards (Adjust for your hardware)
VIDEO_CARDS="intel"
#+end_src

* Installing the Base System
** Preparing Chroot Environment
We need to copy DNS settings and mount pseudo-filesystems so the chroot environment can access the hardware and internet.

#+begin_src bash
cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run
mount --make-slave /mnt/gentoo/run
#+end_src

** Entering the Chroot
#+begin_src bash
chroot /mnt/gentoo /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"
#+end_src

** Syncing Portage
#+begin_src bash
emerge-webrsync
#+end_src

* System Configuration
** Profile, Timezone, and Locale
#+begin_src bash
# Select Systemd profile
eselect profile list
eselect profile set <number>

# Timezone
ln -sf /usr/share/zoneinfo/Canada/Eastern /etc/localtime

# Locale generation
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
localectl set-locale LANG=en_US.UTF-8
#+end_src

** Firmware and Filesystem Tools
Since we are using Btrfs, we *must* install ~btrfs-progs~ so the OS can manage the filesystem. We also need CPU microcode.

#+begin_src bash
emerge --ask sys-kernel/linux-firmware
emerge --ask sys-firmware/intel-microcode
emerge --ask sys-fs/btrfs-progs
#+end_src

* The Kernel
I prefer the ~gentoo-kernel-bin~ for reproducibility and speed. It comes with Btrfs support pre-enabled.

#+begin_src bash
emerge --ask sys-kernel/gentoo-kernel-bin
#+end_src

* Configuring the Bootloader
** Editing Fstab
We need to configure ~fstab~ to mount our Btrfs subvolumes correctly. Use ~blkid~ to find your UUIDs.

#+begin_src bash
nano -w /etc/fstab
#+end_src

#+begin_src conf
# <fs>                  <mountpoint> <type>  <opts>                                       <dump/pass>
UUID=<UUID_ESP>         /efi         vfat    umask=0077                                   0 2
UUID=<UUID_SWAP>        none         swap    sw                                           0 0
UUID=<UUID_ROOT>        /            btrfs   defaults,noatime,compress=zstd,subvol=@      0 0
UUID=<UUID_ROOT>        /home        btrfs   defaults,noatime,compress=zstd,subvol=@home  0 0
#+end_src

** Installing GRUB
#+begin_src bash
emerge --ask sys-boot/grub
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=Gentoo
grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

* Finalizing
** Network and Users
#+begin_src bash
emerge --ask net-misc/networkmanager
systemctl enable NetworkManager

# Set Root Password
passwd

# Create User
useradd -m -G users,wheel,audio,video -s /bin/bash angel
passwd angel
#+end_src

** Reboot
#+begin_src bash
exit
umount -l /mnt/gentoo/dev{/shm,/pts,}
umount -R /mnt/gentoo
reboot
#+end_src
